name = "desugaring"
version = "1.0.0"

[dependencies]
vxml = { "path" = "../vxml" }
writerly = { "path" = "../writerly" }

gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
xmlm = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
ansel = ">= 1.1.0 and < 2.0.0"
on = ">= 1.1.0 and < 2.0.0"
splitter = ">= 1.1.0 and < 2.0.0"
colours = ">= 0.3.0 and < 1.0.0"
input = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
