import desugaring/core as core
import desugaring/desugarers/absorb_backward_one
import desugaring/desugarers/absorb_forward_one
import desugaring/desugarers/absorb_into_previous_sibling
import desugaring/desugarers/add_after_but_not_after_last_child__batch
import desugaring/desugarers/add_before
import desugaring/desugarers/add_before_but_not_before_first_child
import desugaring/desugarers/add_before_but_not_before_first_child__batch
import desugaring/desugarers/add_before_but_not_before_first_of_kind
import desugaring/desugarers/add_before_but_not_before_first_of_kind__batch
import desugaring/desugarers/add_between
import desugaring/desugarers/add_between_all_pairs_2
import desugaring/desugarers/add_between_tag_and_text_node
import desugaring/desugarers/add_between_tag_and_text_node__batch
import desugaring/desugarers/add_between_tags__batch
import desugaring/desugarers/add_class_to_next_sibling
import desugaring/desugarers/add_if_missing_before_but_not_before_first_child
import desugaring/desugarers/append
import desugaring/desugarers/append_attribute
import desugaring/desugarers/append_attribute__batch
import desugaring/desugarers/append_attribute__outside
import desugaring/desugarers/append_attribute_if
import desugaring/desugarers/append_attribute_if_child_of
import desugaring/desugarers/append_attribute_if_child_of__batch
import desugaring/desugarers/append_attribute_if_fancy
import desugaring/desugarers/append_attribute_if_preceded_by_same
import desugaring/desugarers/append_attribute_if_preceded_by_same__outside
import desugaring/desugarers/append_class
import desugaring/desugarers/append_class__batch
import desugaring/desugarers/append_class_to_child_if
import desugaring/desugarers/append_class_to_child_if__batch
import desugaring/desugarers/append_class_to_child_if_has_class
import desugaring/desugarers/append_class_to_child_if_is_not_one_of
import desugaring/desugarers/append_class_to_child_if_is_one_of
import desugaring/desugarers/append_class_to_children_with_class
import desugaring/desugarers/append_class_to_children_with_tag
import desugaring/desugarers/append_custom
import desugaring/desugarers/attribute_drop_prefixes
import desugaring/desugarers/auto_generate_child_if_missing_from_attribute
import desugaring/desugarers/auto_generate_child_if_missing_from_attribute__outside
import desugaring/desugarers/auto_generate_child_if_missing_from_first_descendant_of_type
import desugaring/desugarers/bridge_whitespace
import desugaring/desugarers/bridge_whitespace_single_space
import desugaring/desugarers/check_proper_detokenization
import desugaring/desugarers/check_proper_href_detokenization
import desugaring/desugarers/check_proper_href_tokenization
import desugaring/desugarers/check_proper_tokenization
import desugaring/desugarers/check_tags
import desugaring/desugarers/concatenate_consecutive_lines_if
import desugaring/desugarers/concatenate_text_nodes
import desugaring/desugarers/convert_int_attributes_to_float
import desugaring/desugarers/counters_substitute_and_assign_handles
import desugaring/desugarers/cut_paste_attribute_from_first_child_to_self
import desugaring/desugarers/cut_paste_attribute_from_self_to_child
import desugaring/desugarers/cut_paste_attribute_from_self_to_child__outside
import desugaring/desugarers/delete
import desugaring/desugarers/delete__batch
import desugaring/desugarers/delete_attribute
import desugaring/desugarers/delete_attribute__batch
import desugaring/desugarers/delete_attribute__outside
import desugaring/desugarers/delete_attribute_if
import desugaring/desugarers/delete_attribute_of__batch
import desugaring/desugarers/delete_class
import desugaring/desugarers/delete_empty_lines
import desugaring/desugarers/delete_empty_lines_before_after
import desugaring/desugarers/delete_files_not_used_as_src
import desugaring/desugarers/delete_first_child_occurrences_of_and_recurse
import desugaring/desugarers/delete_if_empty
import desugaring/desugarers/delete_if_empty__batch
import desugaring/desugarers/delete_outside_subtrees
import desugaring/desugarers/delete_text_nodes_with_singleton_empty_line
import desugaring/desugarers/detokenize_all
import desugaring/desugarers/detokenize_href_surroundings
import desugaring/desugarers/dr_create_index
import desugaring/desugarers/dr_create_menu
import desugaring/desugarers/dr_generate_js_course
import desugaring/desugarers/echo_v_if_see_text
import desugaring/desugarers/ensure_attribute_value_starts_with
import desugaring/desugarers/ensure_attribute_value_starts_with_prefix
import desugaring/desugarers/expand_info_attribute
import desugaring/desugarers/expel_initial_last_backward_forward
import desugaring/desugarers/extract_starting_and_ending_spaces
import desugaring/desugarers/filter_nodes_by_key_values
import desugaring/desugarers/filter_nodes_by_key_values_while_saving
import desugaring/desugarers/filter_nodes_by_path_key_values
import desugaring/desugarers/filter_nodes_by_path_key_values_while_saving
import desugaring/desugarers/find_replace
import desugaring/desugarers/find_replace__batch
import desugaring/desugarers/find_replace__batch__outside
import desugaring/desugarers/find_replace__outside
import desugaring/desugarers/find_replace_if_has_ancestor_else
import desugaring/desugarers/find_replace_in_descendants_of__batch
import desugaring/desugarers/fold_children_into_text_if
import desugaring/desugarers/fold_contents_into_text
import desugaring/desugarers/fold_contents_into_text__batch
import desugaring/desugarers/fold_contents_into_text_if
import desugaring/desugarers/fold_custom_into_text
import desugaring/desugarers/fold_into_text
import desugaring/desugarers/fold_into_text__batch
import desugaring/desugarers/footnote_marker_to_sup_handle__outside
import desugaring/desugarers/free_children
import desugaring/desugarers/free_children__batch
import desugaring/desugarers/grand_wrapper_append_attributes
import desugaring/desugarers/grand_wrapper_move_nodes_to_wrapper
import desugaring/desugarers/group_consecutive_children__outside
import desugaring/desugarers/handles_add_ids
import desugaring/desugarers/handles_generate_dictionary
import desugaring/desugarers/handles_generate_dictionary_and_id_list
import desugaring/desugarers/handles_generate_v_definitions_from_t_definitions
import desugaring/desugarers/handles_setup_grand_wrapper
import desugaring/desugarers/handles_substitute
import desugaring/desugarers/handles_warn_unused
import desugaring/desugarers/identity
import desugaring/desugarers/ii2_carousel_component
import desugaring/desugarers/ii2_class_well_container_theorem_2_statement
import desugaring/desugarers/ii2_fix_local_links
import desugaring/desugarers/ii2_generate_table_of_contents_html
import desugaring/desugarers/ii2_insert_counter_commands
import desugaring/desugarers/ii2_normalize_begin_end_align
import desugaring/desugarers/ii2_remove_chapter_number_from_title
import desugaring/desugarers/insert_attribute_as_text
import desugaring/desugarers/insert_attribute_value_at_first_child_start
import desugaring/desugarers/insert_attribute_value_at_start
import desugaring/desugarers/insert_bookend_tags
import desugaring/desugarers/insert_bookend_text_if_no_attributes
import desugaring/desugarers/insert_custom_before_first
import desugaring/desugarers/insert_line_start_end
import desugaring/desugarers/insert_on_own_line_start_end
import desugaring/desugarers/insert_text_start_end
import desugaring/desugarers/insert_text_start_end_if_else
import desugaring/desugarers/insert_text_start_end_if_unique_attr
import desugaring/desugarers/insert_word_joiner_into_adjacent_text_nodes
import desugaring/desugarers/last_to_first_concatenate_text_nodes
import desugaring/desugarers/line_rewrap_no1__outside
import desugaring/desugarers/line_rewrap_no2__outside
import desugaring/desugarers/markdown_link_closing_handrolled_splitter__outside
import desugaring/desugarers/math_label_with_handle_to_mathjax_tag
import desugaring/desugarers/merge_parent_attributes_into_child
import desugaring/desugarers/naive_unescaped_split_and_replace__outside
import desugaring/desugarers/normalize_br_in_pre
import desugaring/desugarers/normalize_math_delimiters_inside
import desugaring/desugarers/normalize_spaces__outside
import desugaring/desugarers/nuke_ancestors
import desugaring/desugarers/pair
import desugaring/desugarers/pair_list_list
import desugaring/desugarers/pour_custom_before_first
import desugaring/desugarers/prepend
import desugaring/desugarers/prepend_append_to_text_children_of
import desugaring/desugarers/prepend_attribute
import desugaring/desugarers/prepend_attribute__outside
import desugaring/desugarers/prepend_attribute_as_first_line
import desugaring/desugarers/prepend_attribute_as_text
import desugaring/desugarers/prepend_attribute_as_wrapped_text
import desugaring/desugarers/prepend_attribute_as_wrapped_text_else_custom
import desugaring/desugarers/prepend_attribute_if
import desugaring/desugarers/prepend_counter_incrementing_attribute
import desugaring/desugarers/prepend_counter_incrementing_attribute__outside
import desugaring/desugarers/prepend_counter_incrementing_attribute_if_fancy
import desugaring/desugarers/prepend_custom
import desugaring/desugarers/prepend_text_node
import desugaring/desugarers/prepend_text_node__batch
import desugaring/desugarers/prepend_text_node__outside
import desugaring/desugarers/prepend_text_node_if_fancy
import desugaring/desugarers/prepend_text_node_if_has_ancestor_else__batch
import desugaring/desugarers/rearrange_links
import desugaring/desugarers/rearrange_links_4_pre_tokenized_src
import desugaring/desugarers/rearrange_links_4_pre_tokenized_src__batch
import desugaring/desugarers/rearrange_links__batch
import desugaring/desugarers/reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node
import desugaring/desugarers/regex_replace
import desugaring/desugarers/regex_replace__batch
import desugaring/desugarers/regex_replace__batch__outside
import desugaring/desugarers/regex_replace__outside
import desugaring/desugarers/regex_split_and_replace__batch__outside
import desugaring/desugarers/regex_split_and_replace__outside
import desugaring/desugarers/reinsert_math_dollar
import desugaring/desugarers/rename
import desugaring/desugarers/rename__batch
import desugaring/desugarers/rename_and_delete_children_if_has_singleton_class_attribute
import desugaring/desugarers/rename_attributes
import desugaring/desugarers/rename_attributes_by_function
import desugaring/desugarers/rename_if_child_of
import desugaring/desugarers/rename_if_child_of__batch
import desugaring/desugarers/rename_if_child_of_one_of
import desugaring/desugarers/rename_if_has_key_value
import desugaring/desugarers/rename_if_has_singleton_class_attribute
import desugaring/desugarers/rename_if_has_singleton_key_value
import desugaring/desugarers/rename_with_appended_attributes_and_prepended_text
import desugaring/desugarers/rename_with_attributes
import desugaring/desugarers/rename_with_attributes__batch
import desugaring/desugarers/rename_with_class
import desugaring/desugarers/rename_with_class_and_attributes
import desugaring/desugarers/replace_in_attribute_values
import desugaring/desugarers/replace_multiple_spaces_by_one
import desugaring/desugarers/replace_with_arbitrary
import desugaring/desugarers/set_handle_value
import desugaring/desugarers/set_handle_value__outside
import desugaring/desugarers/set_handle_value_if_has_ancestor_else
import desugaring/desugarers/split_first_line_after_prefix
import desugaring/desugarers/split_last_line_before_suffix
import desugaring/desugarers/strip_delimiters_inside
import desugaring/desugarers/strip_delimiters_inside_if
import desugaring/desugarers/substitute_class
import desugaring/desugarers/substitute_counters
import desugaring/desugarers/supplement_class
import desugaring/desugarers/surround_elements_by
import desugaring/desugarers/table_marker
import desugaring/desugarers/table_section_header
import desugaring/desugarers/ti2_add_listing_bol_spans
import desugaring/desugarers/ti2_add_prev_next_chapter_title_elements
import desugaring/desugarers/ti2_add_should_be_numbers
import desugaring/desugarers/ti2_adorn_img_with_3003_spans
import desugaring/desugarers/ti2_adorn_with_3003_spans
import desugaring/desugarers/ti2_backfill
import desugaring/desugarers/ti2_create_index
import desugaring/desugarers/ti2_create_menu
import desugaring/desugarers/ti2_cut_paste_width_height_to_descendant_img
import desugaring/desugarers/ti2_expand_carousels
import desugaring/desugarers/ti2_expand_carousels_v2
import desugaring/desugarers/ti2_parse_arbitrary_prompt_response_pre
import desugaring/desugarers/ti2_parse_orange_comments_pre
import desugaring/desugarers/ti2_parse_python_prompt_pre
import desugaring/desugarers/ti2_parse_redyellow_pre
import desugaring/desugarers/ti2_parse_xml_pre
import desugaring/desugarers/ti2_process_pre_listing_classname
import desugaring/desugarers/ti2_turn_lines_into_3003_spans__outside
import desugaring/desugarers/ti2_wrap_with_3003_spans
import desugaring/desugarers/timer
import desugaring/desugarers/tokenize_href_surroundings
import desugaring/desugarers/tokenize_text_children_if
import desugaring/desugarers/trim
import desugaring/desugarers/trim__batch
import desugaring/desugarers/trim_empty_lines
import desugaring/desugarers/trim_empty_lines__batch
import desugaring/desugarers/trim_ending_spaces_except_last_line
import desugaring/desugarers/trim_spaces_around_newlines__outside
import desugaring/desugarers/unescape_delimiters__outside
import desugaring/desugarers/unwrap
import desugaring/desugarers/unwrap__batch
import desugaring/desugarers/unwrap__outside
import desugaring/desugarers/unwrap_if_child_of__batch
import desugaring/desugarers/unwrap_if_descendant_of
import desugaring/desugarers/unwrap_if_descendant_of__batch
import desugaring/desugarers/unwrap_if_first_child
import desugaring/desugarers/unwrap_if_no_child_meets_condition
import desugaring/desugarers/unwrap_if_no_child_meets_condition__batch
import desugaring/desugarers/unwrap_if_unique_child_is
import desugaring/desugarers/unwrap_tags_if_attributes_match
import desugaring/desugarers/unwrap_tags_if_no_attributes
import desugaring/desugarers/unwrap_tags_with_no_text_child
import desugaring/desugarers/unwrap_tags_with_no_text_descendant
import desugaring/desugarers/unwrap_when_zero_or_one_children
import desugaring/desugarers/wrap
import desugaring/desugarers/wrap_adjacent_non_whitespace_text_with
import desugaring/desugarers/wrap_and_custom_steal
import desugaring/desugarers/wrap_and_steal
import desugaring/desugarers/wrap_children
import desugaring/desugarers/wrap_children_avoiding
import desugaring/desugarers/wrap_children_custom
import desugaring/desugarers/wrap_children_up_to
import desugaring/desugarers/wrap_children_up_to_custom
import desugaring/desugarers/wrap_custom
import desugaring/desugarers/wrap_each_child
import desugaring/desugarers/wrap_if_child_of
import desugaring/desugarers/wrap_if_first_child_of
import desugaring/desugarers/wrap_if_not_child_of
import desugaring/desugarers/wrap_if_text_contains
import desugaring/desugarers/wrap_with_custom_if_child_of
import desugaring/desugarers/wrap_with_custom_if_not_child_of

pub const absorb_backward_one = absorb_backward_one.constructor
pub const absorb_forward_one = absorb_forward_one.constructor
pub const absorb_into_previous_sibling = absorb_into_previous_sibling.constructor
pub const add_after_but_not_after_last_child__batch = add_after_but_not_after_last_child__batch.constructor
pub const add_before = add_before.constructor
pub const add_before_but_not_before_first_child = add_before_but_not_before_first_child.constructor
pub const add_before_but_not_before_first_child__batch = add_before_but_not_before_first_child__batch.constructor
pub const add_before_but_not_before_first_of_kind = add_before_but_not_before_first_of_kind.constructor
pub const add_before_but_not_before_first_of_kind__batch = add_before_but_not_before_first_of_kind__batch.constructor
pub const add_between = add_between.constructor
pub const add_between_all_pairs_2 = add_between_all_pairs_2.constructor
pub const add_between_tag_and_text_node = add_between_tag_and_text_node.constructor
pub const add_between_tag_and_text_node__batch = add_between_tag_and_text_node__batch.constructor
pub const add_between_tags__batch = add_between_tags__batch.constructor
pub const add_class_to_next_sibling = add_class_to_next_sibling.constructor
pub const add_if_missing_before_but_not_before_first_child = add_if_missing_before_but_not_before_first_child.constructor
pub const append = append.constructor
pub const append_attribute = append_attribute.constructor
pub const append_attribute__batch = append_attribute__batch.constructor
pub const append_attribute__outside = append_attribute__outside.constructor
pub const append_attribute_if = append_attribute_if.constructor
pub const append_attribute_if_child_of = append_attribute_if_child_of.constructor
pub const append_attribute_if_child_of__batch = append_attribute_if_child_of__batch.constructor
pub const append_attribute_if_fancy = append_attribute_if_fancy.constructor
pub const append_attribute_if_preceded_by_same = append_attribute_if_preceded_by_same.constructor
pub const append_attribute_if_preceded_by_same__outside = append_attribute_if_preceded_by_same__outside.constructor
pub const append_class = append_class.constructor
pub const append_class__batch = append_class__batch.constructor
pub const append_class_to_child_if = append_class_to_child_if.constructor
pub const append_class_to_child_if__batch = append_class_to_child_if__batch.constructor
pub const append_class_to_child_if_has_class = append_class_to_child_if_has_class.constructor
pub const append_class_to_child_if_is_not_one_of = append_class_to_child_if_is_not_one_of.constructor
pub const append_class_to_child_if_is_one_of = append_class_to_child_if_is_one_of.constructor
pub const append_class_to_children_with_class = append_class_to_children_with_class.constructor
pub const append_class_to_children_with_tag = append_class_to_children_with_tag.constructor
pub const append_custom = append_custom.constructor
pub const attribute_drop_prefixes = attribute_drop_prefixes.constructor
pub const auto_generate_child_if_missing_from_attribute = auto_generate_child_if_missing_from_attribute.constructor
pub const auto_generate_child_if_missing_from_attribute__outside = auto_generate_child_if_missing_from_attribute__outside.constructor
pub const auto_generate_child_if_missing_from_first_descendant_of_type = auto_generate_child_if_missing_from_first_descendant_of_type.constructor
pub const bridge_whitespace = bridge_whitespace.constructor
pub const bridge_whitespace_single_space = bridge_whitespace_single_space.constructor
pub const check_proper_detokenization = check_proper_detokenization.constructor
pub const check_proper_href_detokenization = check_proper_href_detokenization.constructor
pub const check_proper_href_tokenization = check_proper_href_tokenization.constructor
pub const check_proper_tokenization = check_proper_tokenization.constructor
pub const check_tags = check_tags.constructor
pub const concatenate_consecutive_lines_if = concatenate_consecutive_lines_if.constructor
pub const concatenate_text_nodes = concatenate_text_nodes.constructor
pub const convert_int_attributes_to_float = convert_int_attributes_to_float.constructor
pub const counters_substitute_and_assign_handles = counters_substitute_and_assign_handles.constructor
pub const cut_paste_attribute_from_first_child_to_self = cut_paste_attribute_from_first_child_to_self.constructor
pub const cut_paste_attribute_from_self_to_child = cut_paste_attribute_from_self_to_child.constructor
pub const cut_paste_attribute_from_self_to_child__outside = cut_paste_attribute_from_self_to_child__outside.constructor
pub const delete = delete.constructor
pub const delete__batch = delete__batch.constructor
pub const delete_attribute = delete_attribute.constructor
pub const delete_attribute__batch = delete_attribute__batch.constructor
pub const delete_attribute__outside = delete_attribute__outside.constructor
pub const delete_attribute_if = delete_attribute_if.constructor
pub const delete_attribute_of__batch = delete_attribute_of__batch.constructor
pub const delete_class = delete_class.constructor
pub const delete_empty_lines = delete_empty_lines.constructor
pub const delete_empty_lines_before_after = delete_empty_lines_before_after.constructor
pub const delete_files_not_used_as_src = delete_files_not_used_as_src.constructor
pub const delete_first_child_occurrences_of_and_recurse = delete_first_child_occurrences_of_and_recurse.constructor
pub const delete_if_empty = delete_if_empty.constructor
pub const delete_if_empty__batch = delete_if_empty__batch.constructor
pub const delete_outside_subtrees = delete_outside_subtrees.constructor
pub const delete_text_nodes_with_singleton_empty_line = delete_text_nodes_with_singleton_empty_line.constructor
pub const detokenize_all = detokenize_all.constructor
pub const detokenize_href_surroundings = detokenize_href_surroundings.constructor
pub const dr_create_index = dr_create_index.constructor
pub const dr_create_menu = dr_create_menu.constructor
pub const dr_generate_js_course = dr_generate_js_course.constructor
pub const echo_v_if_see_text = echo_v_if_see_text.constructor
pub const ensure_attribute_value_starts_with = ensure_attribute_value_starts_with.constructor
pub const ensure_attribute_value_starts_with_prefix = ensure_attribute_value_starts_with_prefix.constructor
pub const expand_info_attribute = expand_info_attribute.constructor
pub const expel_initial_last_backward_forward = expel_initial_last_backward_forward.constructor
pub const extract_starting_and_ending_spaces = extract_starting_and_ending_spaces.constructor
pub const filter_nodes_by_key_values = filter_nodes_by_key_values.constructor
pub const filter_nodes_by_key_values_while_saving = filter_nodes_by_key_values_while_saving.constructor
pub const filter_nodes_by_path_key_values = filter_nodes_by_path_key_values.constructor
pub const filter_nodes_by_path_key_values_while_saving = filter_nodes_by_path_key_values_while_saving.constructor
pub const find_replace = find_replace.constructor
pub const find_replace__batch = find_replace__batch.constructor
pub const find_replace__batch__outside = find_replace__batch__outside.constructor
pub const find_replace__outside = find_replace__outside.constructor
pub const find_replace_if_has_ancestor_else = find_replace_if_has_ancestor_else.constructor
pub const find_replace_in_descendants_of__batch = find_replace_in_descendants_of__batch.constructor
pub const fold_children_into_text_if = fold_children_into_text_if.constructor
pub const fold_contents_into_text = fold_contents_into_text.constructor
pub const fold_contents_into_text__batch = fold_contents_into_text__batch.constructor
pub const fold_contents_into_text_if = fold_contents_into_text_if.constructor
pub const fold_custom_into_text = fold_custom_into_text.constructor
pub const fold_into_text = fold_into_text.constructor
pub const fold_into_text__batch = fold_into_text__batch.constructor
pub const footnote_marker_to_sup_handle__outside = footnote_marker_to_sup_handle__outside.constructor
pub const free_children = free_children.constructor
pub const free_children__batch = free_children__batch.constructor
pub const grand_wrapper_append_attributes = grand_wrapper_append_attributes.constructor
pub const grand_wrapper_move_nodes_to_wrapper = grand_wrapper_move_nodes_to_wrapper.constructor
pub const group_consecutive_children__outside = group_consecutive_children__outside.constructor
pub const handles_add_ids = handles_add_ids.constructor
pub const handles_generate_dictionary = handles_generate_dictionary.constructor
pub const handles_generate_dictionary_and_id_list = handles_generate_dictionary_and_id_list.constructor
pub const handles_generate_v_definitions_from_t_definitions = handles_generate_v_definitions_from_t_definitions.constructor
pub const handles_setup_grand_wrapper = handles_setup_grand_wrapper.constructor
pub const handles_substitute = handles_substitute.constructor
pub const handles_warn_unused = handles_warn_unused.constructor
pub const identity = identity.constructor
pub const ii2_carousel_component = ii2_carousel_component.constructor
pub const ii2_class_well_container_theorem_2_statement = ii2_class_well_container_theorem_2_statement.constructor
pub const ii2_fix_local_links = ii2_fix_local_links.constructor
pub const ii2_generate_table_of_contents_html = ii2_generate_table_of_contents_html.constructor
pub const ii2_insert_counter_commands = ii2_insert_counter_commands.constructor
pub const ii2_normalize_begin_end_align = ii2_normalize_begin_end_align.constructor
pub const ii2_remove_chapter_number_from_title = ii2_remove_chapter_number_from_title.constructor
pub const insert_attribute_as_text = insert_attribute_as_text.constructor
pub const insert_attribute_value_at_first_child_start = insert_attribute_value_at_first_child_start.constructor
pub const insert_attribute_value_at_start = insert_attribute_value_at_start.constructor
pub const insert_bookend_tags = insert_bookend_tags.constructor
pub const insert_bookend_text_if_no_attributes = insert_bookend_text_if_no_attributes.constructor
pub const insert_custom_before_first = insert_custom_before_first.constructor
pub const insert_line_start_end = insert_line_start_end.constructor
pub const insert_on_own_line_start_end = insert_on_own_line_start_end.constructor
pub const insert_text_start_end = insert_text_start_end.constructor
pub const insert_text_start_end_if_else = insert_text_start_end_if_else.constructor
pub const insert_text_start_end_if_unique_attr = insert_text_start_end_if_unique_attr.constructor
pub const insert_word_joiner_into_adjacent_text_nodes = insert_word_joiner_into_adjacent_text_nodes.constructor
pub const last_to_first_concatenate_text_nodes = last_to_first_concatenate_text_nodes.constructor
pub const line_rewrap_no1__outside = line_rewrap_no1__outside.constructor
pub const line_rewrap_no2__outside = line_rewrap_no2__outside.constructor
pub const markdown_link_closing_handrolled_splitter__outside = markdown_link_closing_handrolled_splitter__outside.constructor
pub const math_label_with_handle_to_mathjax_tag = math_label_with_handle_to_mathjax_tag.constructor
pub const merge_parent_attributes_into_child = merge_parent_attributes_into_child.constructor
pub const naive_unescaped_split_and_replace__outside = naive_unescaped_split_and_replace__outside.constructor
pub const normalize_br_in_pre = normalize_br_in_pre.constructor
pub const normalize_math_delimiters_inside = normalize_math_delimiters_inside.constructor
pub const normalize_spaces__outside = normalize_spaces__outside.constructor
pub const nuke_ancestors = nuke_ancestors.constructor
pub const pair = pair.constructor
pub const pair_list_list = pair_list_list.constructor
pub const pour_custom_before_first = pour_custom_before_first.constructor
pub const prepend = prepend.constructor
pub const prepend_append_to_text_children_of = prepend_append_to_text_children_of.constructor
pub const prepend_attribute = prepend_attribute.constructor
pub const prepend_attribute__outside = prepend_attribute__outside.constructor
pub const prepend_attribute_as_first_line = prepend_attribute_as_first_line.constructor
pub const prepend_attribute_as_text = prepend_attribute_as_text.constructor
pub const prepend_attribute_as_wrapped_text = prepend_attribute_as_wrapped_text.constructor
pub const prepend_attribute_as_wrapped_text_else_custom = prepend_attribute_as_wrapped_text_else_custom.constructor
pub const prepend_attribute_if = prepend_attribute_if.constructor
pub const prepend_counter_incrementing_attribute = prepend_counter_incrementing_attribute.constructor
pub const prepend_counter_incrementing_attribute__outside = prepend_counter_incrementing_attribute__outside.constructor
pub const prepend_counter_incrementing_attribute_if_fancy = prepend_counter_incrementing_attribute_if_fancy.constructor
pub const prepend_custom = prepend_custom.constructor
pub const prepend_text_node = prepend_text_node.constructor
pub const prepend_text_node__batch = prepend_text_node__batch.constructor
pub const prepend_text_node__outside = prepend_text_node__outside.constructor
pub const prepend_text_node_if_fancy = prepend_text_node_if_fancy.constructor
pub const prepend_text_node_if_has_ancestor_else__batch = prepend_text_node_if_has_ancestor_else__batch.constructor
pub const rearrange_links = rearrange_links.constructor
pub const rearrange_links_4_pre_tokenized_src = rearrange_links_4_pre_tokenized_src.constructor
pub const rearrange_links_4_pre_tokenized_src__batch = rearrange_links_4_pre_tokenized_src__batch.constructor
pub const rearrange_links__batch = rearrange_links__batch.constructor
pub const reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node = reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node.constructor
pub const regex_replace = regex_replace.constructor
pub const regex_replace__batch = regex_replace__batch.constructor
pub const regex_replace__batch__outside = regex_replace__batch__outside.constructor
pub const regex_replace__outside = regex_replace__outside.constructor
pub const regex_split_and_replace__batch__outside = regex_split_and_replace__batch__outside.constructor
pub const regex_split_and_replace__outside = regex_split_and_replace__outside.constructor
pub const reinsert_math_dollar = reinsert_math_dollar.constructor
pub const rename = rename.constructor
pub const rename__batch = rename__batch.constructor
pub const rename_and_delete_children_if_has_singleton_class_attribute = rename_and_delete_children_if_has_singleton_class_attribute.constructor
pub const rename_attributes = rename_attributes.constructor
pub const rename_attributes_by_function = rename_attributes_by_function.constructor
pub const rename_if_child_of = rename_if_child_of.constructor
pub const rename_if_child_of__batch = rename_if_child_of__batch.constructor
pub const rename_if_child_of_one_of = rename_if_child_of_one_of.constructor
pub const rename_if_has_key_value = rename_if_has_key_value.constructor
pub const rename_if_has_singleton_class_attribute = rename_if_has_singleton_class_attribute.constructor
pub const rename_if_has_singleton_key_value = rename_if_has_singleton_key_value.constructor
pub const rename_with_appended_attributes_and_prepended_text = rename_with_appended_attributes_and_prepended_text.constructor
pub const rename_with_attributes = rename_with_attributes.constructor
pub const rename_with_attributes__batch = rename_with_attributes__batch.constructor
pub const rename_with_class = rename_with_class.constructor
pub const rename_with_class_and_attributes = rename_with_class_and_attributes.constructor
pub const replace_in_attribute_values = replace_in_attribute_values.constructor
pub const replace_multiple_spaces_by_one = replace_multiple_spaces_by_one.constructor
pub const replace_with_arbitrary = replace_with_arbitrary.constructor
pub const set_handle_value = set_handle_value.constructor
pub const set_handle_value__outside = set_handle_value__outside.constructor
pub const set_handle_value_if_has_ancestor_else = set_handle_value_if_has_ancestor_else.constructor
pub const split_first_line_after_prefix = split_first_line_after_prefix.constructor
pub const split_last_line_before_suffix = split_last_line_before_suffix.constructor
pub const strip_delimiters_inside = strip_delimiters_inside.constructor
pub const strip_delimiters_inside_if = strip_delimiters_inside_if.constructor
pub const substitute_class = substitute_class.constructor
pub const substitute_counters = substitute_counters.constructor
pub const supplement_class = supplement_class.constructor
pub const surround_elements_by = surround_elements_by.constructor
pub const table_marker = table_marker.constructor
pub const table_section_header = table_section_header.constructor
pub const ti2_add_listing_bol_spans = ti2_add_listing_bol_spans.constructor
pub const ti2_add_prev_next_chapter_title_elements = ti2_add_prev_next_chapter_title_elements.constructor
pub const ti2_add_should_be_numbers = ti2_add_should_be_numbers.constructor
pub const ti2_adorn_img_with_3003_spans = ti2_adorn_img_with_3003_spans.constructor
pub const ti2_adorn_with_3003_spans = ti2_adorn_with_3003_spans.constructor
pub const ti2_backfill = ti2_backfill.constructor
pub const ti2_create_index = ti2_create_index.constructor
pub const ti2_create_menu = ti2_create_menu.constructor
pub const ti2_cut_paste_width_height_to_descendant_img = ti2_cut_paste_width_height_to_descendant_img.constructor
pub const ti2_expand_carousels = ti2_expand_carousels.constructor
pub const ti2_expand_carousels_v2 = ti2_expand_carousels_v2.constructor
pub const ti2_parse_arbitrary_prompt_response_pre = ti2_parse_arbitrary_prompt_response_pre.constructor
pub const ti2_parse_orange_comments_pre = ti2_parse_orange_comments_pre.constructor
pub const ti2_parse_python_prompt_pre = ti2_parse_python_prompt_pre.constructor
pub const ti2_parse_redyellow_pre = ti2_parse_redyellow_pre.constructor
pub const ti2_parse_xml_pre = ti2_parse_xml_pre.constructor
pub const ti2_process_pre_listing_classname = ti2_process_pre_listing_classname.constructor
pub const ti2_turn_lines_into_3003_spans__outside = ti2_turn_lines_into_3003_spans__outside.constructor
pub const ti2_wrap_with_3003_spans = ti2_wrap_with_3003_spans.constructor
pub const timer = timer.constructor
pub const tokenize_href_surroundings = tokenize_href_surroundings.constructor
pub const tokenize_text_children_if = tokenize_text_children_if.constructor
pub const trim = trim.constructor
pub const trim__batch = trim__batch.constructor
pub const trim_empty_lines = trim_empty_lines.constructor
pub const trim_empty_lines__batch = trim_empty_lines__batch.constructor
pub const trim_ending_spaces_except_last_line = trim_ending_spaces_except_last_line.constructor
pub const trim_spaces_around_newlines__outside = trim_spaces_around_newlines__outside.constructor
pub const unescape_delimiters__outside = unescape_delimiters__outside.constructor
pub const unwrap = unwrap.constructor
pub const unwrap__batch = unwrap__batch.constructor
pub const unwrap__outside = unwrap__outside.constructor
pub const unwrap_if_child_of__batch = unwrap_if_child_of__batch.constructor
pub const unwrap_if_descendant_of = unwrap_if_descendant_of.constructor
pub const unwrap_if_descendant_of__batch = unwrap_if_descendant_of__batch.constructor
pub const unwrap_if_first_child = unwrap_if_first_child.constructor
pub const unwrap_if_no_child_meets_condition = unwrap_if_no_child_meets_condition.constructor
pub const unwrap_if_no_child_meets_condition__batch = unwrap_if_no_child_meets_condition__batch.constructor
pub const unwrap_if_unique_child_is = unwrap_if_unique_child_is.constructor
pub const unwrap_tags_if_attributes_match = unwrap_tags_if_attributes_match.constructor
pub const unwrap_tags_if_no_attributes = unwrap_tags_if_no_attributes.constructor
pub const unwrap_tags_with_no_text_child = unwrap_tags_with_no_text_child.constructor
pub const unwrap_tags_with_no_text_descendant = unwrap_tags_with_no_text_descendant.constructor
pub const unwrap_when_zero_or_one_children = unwrap_when_zero_or_one_children.constructor
pub const wrap = wrap.constructor
pub const wrap_adjacent_non_whitespace_text_with = wrap_adjacent_non_whitespace_text_with.constructor
pub const wrap_and_custom_steal = wrap_and_custom_steal.constructor
pub const wrap_and_steal = wrap_and_steal.constructor
pub const wrap_children = wrap_children.constructor
pub const wrap_children_avoiding = wrap_children_avoiding.constructor
pub const wrap_children_custom = wrap_children_custom.constructor
pub const wrap_children_up_to = wrap_children_up_to.constructor
pub const wrap_children_up_to_custom = wrap_children_up_to_custom.constructor
pub const wrap_custom = wrap_custom.constructor
pub const wrap_each_child = wrap_each_child.constructor
pub const wrap_if_child_of = wrap_if_child_of.constructor
pub const wrap_if_first_child_of = wrap_if_first_child_of.constructor
pub const wrap_if_not_child_of = wrap_if_not_child_of.constructor
pub const wrap_if_text_contains = wrap_if_text_contains.constructor
pub const wrap_with_custom_if_child_of = wrap_with_custom_if_child_of.constructor
pub const wrap_with_custom_if_not_child_of = wrap_with_custom_if_not_child_of.constructor

pub const assertive_tests : List(fn() -> core.AssertiveTestCollection) = [
  absorb_backward_one.assertive_tests,
  absorb_forward_one.assertive_tests,
  absorb_into_previous_sibling.assertive_tests,
  add_after_but_not_after_last_child__batch.assertive_tests,
  add_before.assertive_tests,
  add_before_but_not_before_first_child.assertive_tests,
  add_before_but_not_before_first_child__batch.assertive_tests,
  add_before_but_not_before_first_of_kind.assertive_tests,
  add_before_but_not_before_first_of_kind__batch.assertive_tests,
  add_between.assertive_tests,
  add_between_all_pairs_2.assertive_tests,
  add_between_tag_and_text_node.assertive_tests,
  add_between_tag_and_text_node__batch.assertive_tests,
  add_between_tags__batch.assertive_tests,
  add_class_to_next_sibling.assertive_tests,
  add_if_missing_before_but_not_before_first_child.assertive_tests,
  append.assertive_tests,
  append_attribute.assertive_tests,
  append_attribute__batch.assertive_tests,
  append_attribute__outside.assertive_tests,
  append_attribute_if.assertive_tests,
  append_attribute_if_child_of.assertive_tests,
  append_attribute_if_child_of__batch.assertive_tests,
  append_attribute_if_fancy.assertive_tests,
  append_attribute_if_preceded_by_same.assertive_tests,
  append_attribute_if_preceded_by_same__outside.assertive_tests,
  append_class.assertive_tests,
  append_class__batch.assertive_tests,
  append_class_to_child_if.assertive_tests,
  append_class_to_child_if__batch.assertive_tests,
  append_class_to_child_if_has_class.assertive_tests,
  append_class_to_child_if_is_not_one_of.assertive_tests,
  append_class_to_child_if_is_one_of.assertive_tests,
  append_class_to_children_with_class.assertive_tests,
  append_class_to_children_with_tag.assertive_tests,
  append_custom.assertive_tests,
  attribute_drop_prefixes.assertive_tests,
  auto_generate_child_if_missing_from_attribute.assertive_tests,
  auto_generate_child_if_missing_from_attribute__outside.assertive_tests,
  auto_generate_child_if_missing_from_first_descendant_of_type.assertive_tests,
  bridge_whitespace.assertive_tests,
  bridge_whitespace_single_space.assertive_tests,
  check_proper_detokenization.assertive_tests,
  check_proper_href_detokenization.assertive_tests,
  check_proper_href_tokenization.assertive_tests,
  check_proper_tokenization.assertive_tests,
  check_tags.assertive_tests,
  concatenate_consecutive_lines_if.assertive_tests,
  concatenate_text_nodes.assertive_tests,
  convert_int_attributes_to_float.assertive_tests,
  counters_substitute_and_assign_handles.assertive_tests,
  cut_paste_attribute_from_first_child_to_self.assertive_tests,
  cut_paste_attribute_from_self_to_child.assertive_tests,
  cut_paste_attribute_from_self_to_child__outside.assertive_tests,
  delete.assertive_tests,
  delete__batch.assertive_tests,
  delete_attribute.assertive_tests,
  delete_attribute__batch.assertive_tests,
  delete_attribute__outside.assertive_tests,
  delete_attribute_if.assertive_tests,
  delete_attribute_of__batch.assertive_tests,
  delete_class.assertive_tests,
  delete_empty_lines.assertive_tests,
  delete_empty_lines_before_after.assertive_tests,
  delete_files_not_used_as_src.assertive_tests,
  delete_first_child_occurrences_of_and_recurse.assertive_tests,
  delete_if_empty.assertive_tests,
  delete_if_empty__batch.assertive_tests,
  delete_outside_subtrees.assertive_tests,
  delete_text_nodes_with_singleton_empty_line.assertive_tests,
  detokenize_all.assertive_tests,
  detokenize_href_surroundings.assertive_tests,
  dr_create_index.assertive_tests,
  dr_create_menu.assertive_tests,
  dr_generate_js_course.assertive_tests,
  echo_v_if_see_text.assertive_tests,
  ensure_attribute_value_starts_with.assertive_tests,
  ensure_attribute_value_starts_with_prefix.assertive_tests,
  expand_info_attribute.assertive_tests,
  expel_initial_last_backward_forward.assertive_tests,
  extract_starting_and_ending_spaces.assertive_tests,
  filter_nodes_by_key_values.assertive_tests,
  filter_nodes_by_key_values_while_saving.assertive_tests,
  filter_nodes_by_path_key_values.assertive_tests,
  filter_nodes_by_path_key_values_while_saving.assertive_tests,
  find_replace.assertive_tests,
  find_replace__batch.assertive_tests,
  find_replace__batch__outside.assertive_tests,
  find_replace__outside.assertive_tests,
  find_replace_if_has_ancestor_else.assertive_tests,
  find_replace_in_descendants_of__batch.assertive_tests,
  fold_children_into_text_if.assertive_tests,
  fold_contents_into_text.assertive_tests,
  fold_contents_into_text__batch.assertive_tests,
  fold_contents_into_text_if.assertive_tests,
  fold_custom_into_text.assertive_tests,
  fold_into_text.assertive_tests,
  fold_into_text__batch.assertive_tests,
  footnote_marker_to_sup_handle__outside.assertive_tests,
  free_children.assertive_tests,
  free_children__batch.assertive_tests,
  grand_wrapper_append_attributes.assertive_tests,
  grand_wrapper_move_nodes_to_wrapper.assertive_tests,
  group_consecutive_children__outside.assertive_tests,
  handles_add_ids.assertive_tests,
  handles_generate_dictionary.assertive_tests,
  handles_generate_dictionary_and_id_list.assertive_tests,
  handles_generate_v_definitions_from_t_definitions.assertive_tests,
  handles_setup_grand_wrapper.assertive_tests,
  handles_substitute.assertive_tests,
  handles_warn_unused.assertive_tests,
  identity.assertive_tests,
  ii2_carousel_component.assertive_tests,
  ii2_class_well_container_theorem_2_statement.assertive_tests,
  ii2_fix_local_links.assertive_tests,
  ii2_generate_table_of_contents_html.assertive_tests,
  ii2_insert_counter_commands.assertive_tests,
  ii2_normalize_begin_end_align.assertive_tests,
  ii2_remove_chapter_number_from_title.assertive_tests,
  insert_attribute_as_text.assertive_tests,
  insert_attribute_value_at_first_child_start.assertive_tests,
  insert_attribute_value_at_start.assertive_tests,
  insert_bookend_tags.assertive_tests,
  insert_bookend_text_if_no_attributes.assertive_tests,
  insert_custom_before_first.assertive_tests,
  insert_line_start_end.assertive_tests,
  insert_on_own_line_start_end.assertive_tests,
  insert_text_start_end.assertive_tests,
  insert_text_start_end_if_else.assertive_tests,
  insert_text_start_end_if_unique_attr.assertive_tests,
  insert_word_joiner_into_adjacent_text_nodes.assertive_tests,
  last_to_first_concatenate_text_nodes.assertive_tests,
  line_rewrap_no1__outside.assertive_tests,
  line_rewrap_no2__outside.assertive_tests,
  markdown_link_closing_handrolled_splitter__outside.assertive_tests,
  math_label_with_handle_to_mathjax_tag.assertive_tests,
  merge_parent_attributes_into_child.assertive_tests,
  naive_unescaped_split_and_replace__outside.assertive_tests,
  normalize_br_in_pre.assertive_tests,
  normalize_math_delimiters_inside.assertive_tests,
  normalize_spaces__outside.assertive_tests,
  nuke_ancestors.assertive_tests,
  pair.assertive_tests,
  pair_list_list.assertive_tests,
  pour_custom_before_first.assertive_tests,
  prepend.assertive_tests,
  prepend_append_to_text_children_of.assertive_tests,
  prepend_attribute.assertive_tests,
  prepend_attribute__outside.assertive_tests,
  prepend_attribute_as_first_line.assertive_tests,
  prepend_attribute_as_text.assertive_tests,
  prepend_attribute_as_wrapped_text.assertive_tests,
  prepend_attribute_as_wrapped_text_else_custom.assertive_tests,
  prepend_attribute_if.assertive_tests,
  prepend_counter_incrementing_attribute.assertive_tests,
  prepend_counter_incrementing_attribute__outside.assertive_tests,
  prepend_counter_incrementing_attribute_if_fancy.assertive_tests,
  prepend_custom.assertive_tests,
  prepend_text_node.assertive_tests,
  prepend_text_node__batch.assertive_tests,
  prepend_text_node__outside.assertive_tests,
  prepend_text_node_if_fancy.assertive_tests,
  prepend_text_node_if_has_ancestor_else__batch.assertive_tests,
  rearrange_links.assertive_tests,
  rearrange_links_4_pre_tokenized_src.assertive_tests,
  rearrange_links_4_pre_tokenized_src__batch.assertive_tests,
  rearrange_links__batch.assertive_tests,
  reassign_text_node_blame_to_blame_of_first_nonempty_line_in_text_node.assertive_tests,
  regex_replace.assertive_tests,
  regex_replace__batch.assertive_tests,
  regex_replace__batch__outside.assertive_tests,
  regex_replace__outside.assertive_tests,
  regex_split_and_replace__batch__outside.assertive_tests,
  regex_split_and_replace__outside.assertive_tests,
  reinsert_math_dollar.assertive_tests,
  rename.assertive_tests,
  rename__batch.assertive_tests,
  rename_and_delete_children_if_has_singleton_class_attribute.assertive_tests,
  rename_attributes.assertive_tests,
  rename_attributes_by_function.assertive_tests,
  rename_if_child_of.assertive_tests,
  rename_if_child_of__batch.assertive_tests,
  rename_if_child_of_one_of.assertive_tests,
  rename_if_has_key_value.assertive_tests,
  rename_if_has_singleton_class_attribute.assertive_tests,
  rename_if_has_singleton_key_value.assertive_tests,
  rename_with_appended_attributes_and_prepended_text.assertive_tests,
  rename_with_attributes.assertive_tests,
  rename_with_attributes__batch.assertive_tests,
  rename_with_class.assertive_tests,
  rename_with_class_and_attributes.assertive_tests,
  replace_in_attribute_values.assertive_tests,
  replace_multiple_spaces_by_one.assertive_tests,
  replace_with_arbitrary.assertive_tests,
  set_handle_value.assertive_tests,
  set_handle_value__outside.assertive_tests,
  set_handle_value_if_has_ancestor_else.assertive_tests,
  split_first_line_after_prefix.assertive_tests,
  split_last_line_before_suffix.assertive_tests,
  strip_delimiters_inside.assertive_tests,
  strip_delimiters_inside_if.assertive_tests,
  substitute_class.assertive_tests,
  substitute_counters.assertive_tests,
  supplement_class.assertive_tests,
  surround_elements_by.assertive_tests,
  table_marker.assertive_tests,
  table_section_header.assertive_tests,
  ti2_add_listing_bol_spans.assertive_tests,
  ti2_add_prev_next_chapter_title_elements.assertive_tests,
  ti2_add_should_be_numbers.assertive_tests,
  ti2_adorn_img_with_3003_spans.assertive_tests,
  ti2_adorn_with_3003_spans.assertive_tests,
  ti2_backfill.assertive_tests,
  ti2_create_index.assertive_tests,
  ti2_create_menu.assertive_tests,
  ti2_cut_paste_width_height_to_descendant_img.assertive_tests,
  ti2_expand_carousels.assertive_tests,
  ti2_expand_carousels_v2.assertive_tests,
  ti2_parse_arbitrary_prompt_response_pre.assertive_tests,
  ti2_parse_orange_comments_pre.assertive_tests,
  ti2_parse_python_prompt_pre.assertive_tests,
  ti2_parse_redyellow_pre.assertive_tests,
  ti2_parse_xml_pre.assertive_tests,
  ti2_process_pre_listing_classname.assertive_tests,
  ti2_turn_lines_into_3003_spans__outside.assertive_tests,
  ti2_wrap_with_3003_spans.assertive_tests,
  timer.assertive_tests,
  tokenize_href_surroundings.assertive_tests,
  tokenize_text_children_if.assertive_tests,
  trim.assertive_tests,
  trim__batch.assertive_tests,
  trim_empty_lines.assertive_tests,
  trim_empty_lines__batch.assertive_tests,
  trim_ending_spaces_except_last_line.assertive_tests,
  trim_spaces_around_newlines__outside.assertive_tests,
  unescape_delimiters__outside.assertive_tests,
  unwrap.assertive_tests,
  unwrap__batch.assertive_tests,
  unwrap__outside.assertive_tests,
  unwrap_if_child_of__batch.assertive_tests,
  unwrap_if_descendant_of.assertive_tests,
  unwrap_if_descendant_of__batch.assertive_tests,
  unwrap_if_first_child.assertive_tests,
  unwrap_if_no_child_meets_condition.assertive_tests,
  unwrap_if_no_child_meets_condition__batch.assertive_tests,
  unwrap_if_unique_child_is.assertive_tests,
  unwrap_tags_if_attributes_match.assertive_tests,
  unwrap_tags_if_no_attributes.assertive_tests,
  unwrap_tags_with_no_text_child.assertive_tests,
  unwrap_tags_with_no_text_descendant.assertive_tests,
  unwrap_when_zero_or_one_children.assertive_tests,
  wrap.assertive_tests,
  wrap_adjacent_non_whitespace_text_with.assertive_tests,
  wrap_and_custom_steal.assertive_tests,
  wrap_and_steal.assertive_tests,
  wrap_children.assertive_tests,
  wrap_children_avoiding.assertive_tests,
  wrap_children_custom.assertive_tests,
  wrap_children_up_to.assertive_tests,
  wrap_children_up_to_custom.assertive_tests,
  wrap_custom.assertive_tests,
  wrap_each_child.assertive_tests,
  wrap_if_child_of.assertive_tests,
  wrap_if_first_child_of.assertive_tests,
  wrap_if_not_child_of.assertive_tests,
  wrap_if_text_contains.assertive_tests,
  wrap_with_custom_if_child_of.assertive_tests,
  wrap_with_custom_if_not_child_of.assertive_tests,
]
